### ISSUE TITLE
Global / Index (Login): Allows user to login without credentials

### ISSUE THREAD

**Issue by zaralev** [zaralev/UXII_HappySunshine#1]
Global
Page: Index (Login)
URL: http://zaralev.github.io/UXII_HappySunshine/lowFidelity/
Viewport: All

If you don't type any username or password, it allows you to login and view menu. If you go to create an account, no matter what you do, it allows you to login and view menu.

**Comment by torres-diego** [comment]
login and create an account local storage should be good to go.
